# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: [main, deps]
  pull_request:
    branches: [main, deps]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@877e3e063288d17fbfd7819a7417f3d0bedaf1f0
        with:
          deno-version: v1.18.1

      - name: Verify formatting
        run: cd api && deno fmt --check

      - name: Run linter
        run: cd api && deno lint

      - name: Compile
        run: cd api &&  deno run --allow-read --allow-write ./createRoutes.ts && deno compile --no-check="remote" --importmap="./importmap.json" --unstable -A ./mod.ts
