# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, deps ]
  pull_request:
    branches: [ main, deps ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@2270f39ef63c3edf50be34da68c039eca5e15c15
      with:
        version: 6.27.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'pnpm'
    - run: pnpm i
    - run: pnpm v:build
    - run: pnpm v:lint
    - run: pnpm v:fmt:check
    - run: pnpm v:types
